Add node-latest-aliases job to canary workflow

diff --git a/.github/workflows/canary.yml b/.github/workflows/canary.yml
--- a/.github/workflows/canary.yml
+++ b/.github/workflows/canary.yml
@@ -40,3 +40,34 @@ jobs:
           majorVersion=$(echo $canaryVersion | cut -d- -f1)
           __tests__/verify-node.sh "$majorVersion"
         shell: bash
+        
+  node-latest-aliases:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [macos-latest]
+        node-version: [current, latest, node]
+    steps:
+      - name: Get node version
+        run: |
+          latestNodeVersion=$(curl https://nodejs.org/dist/index.json | jq -r '. [0].version')
+          echo "LATEST_NODE_VERSION=$latestNodeVersion" >> $GITHUB_OUTPUT
+        id: version
+        shell: bash
+      - uses: actions/checkout@v5
+      - name: Setup Node
+        uses: actions/setup-node@v5
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: Retrieve version after install
+        run: |
+          updatedVersion=$(echo $(node --version))
+          echo "NODE_VERSION_UPDATED=$updatedVersion" >> $GITHUB_OUTPUT
+        id: updatedVersion
+        shell: bash
+      - name: Compare versions
+        if: ${{ steps.version.outputs.LATEST_NODE_VERSION != steps.updatedVersion.outputs.NODE_VERSION_UPDATED}}
+        run: |
+          echo "Latest node version failed to download."
+          exit 1
